Dalokae/mac-playbook

roles/dotfiles/templates/zshrc.j2
see https://twitter.com/ThisIsFlorianK/status/1057242469891497984
=> add extract plugin for oh my zsh

playbooks/setup.yml, roles/common/tasks/main.yml, roles/upgrade/tasks/main.yml
Role `php` is configured to install php 7.2 but this fails because :
* package `php`(7.2) is installed
* dev upgrade
* upgrade all binaries -> package php is updated to 7.3
* install php -> install package `php@7.2`
* PHP 7.2 and 7.3 are installed
With this fix:
* package `php`(7.2) is installed
* dev upgrade
* install php -> install package `php@7.2`
* upgrade all binaries -> no upgrade for php package
* PHP 7.2 is installed
=> move upgrade tasks to a specific role to avoid issue with php upgrade

roles/dotfiles/templates/zshrc.j2
=> Run composer vendor binaries without typing vendor/bin

roles/common/vars/main.yml
Fix the following issue:
```
Error: Cask java8 exists in multiple taps:
homebrew/cask-versions/java8
caskroom/versions/java8
```
Ref: https://github.com/Homebrew/homebrew-cask/issues/41990#issuecomment-389009850.
=> Use homebrew/cask-* instead of caskroom/*

roles/common/tasks/main.yml, roles/common/vars/main.yml
Fix the following error:
```
Error: invalid option: --with-openssl
```
`--with-openssl` option have been removed from curl formula (see https://github.com/Homebrew/homebrew-core/commit/0bfb0391d7c2db964a2da4d31a2495d91361df8a#diff-a7a59ba41131628f779debf43858c613).
=> Fix issue while trying to install curl with option --with-openssl

roles/nginx/templates/conf/laravel.j2, roles/nginx/templates/conf/symfony-flex.j2, roles/nginx/templates/conf/symfony.j2, roles/nginx/templates/conf/wordpress.j2
I can't remember why we added this location block. But it seem's that this was a hack for missing things or to protect us against strange browser behaviors.
=> Remove nginx specific location block for favicon

roles/dotfiles/tasks/main.yml, roles/dotfiles/templates/editorconfig.j2
Add a global file in the $HOME to apply editorconfig to all projects without specific config.
=> Add global editorconfig

roles/cleanup/tasks/main.yml
https://app.clubhouse.io/wizifarm/story/6082/lors-d-un-brew-cleanup-les-anciennes-version-de-lib-n-ont-pas-l-air-d-%C3%AAtre-supprim%C3%A9es
=> Add gem cleanup

roles/cleanup/tasks/main.yml
I don't know what was the purpose of the `yes |` part of the command, but it was the cause of the problem.
Fix #48.
=> Fix gem cleanup hanging on "yes"

Makefile, roles/common/vars/main.yml
It's temporary waiting for a fix on the Apple or Homebrew side.
#53
=> Add target to fix python crash with macOS Catalina 10.15

default.config.yml, roles/dotfiles/tasks/main.yml, roles/dotfiles/templates/zshrc.j2
https://github.com/zsh-users/zsh-autosuggestions
#50 
By default the plugin is disabled
=> Add zsh-autosuggestions

roles/dotfiles/tasks/main.yml, roles/dotfiles/templates/zshrc.j2
Fix #51
I create a basic plugin for OhMyZsh and Symfony, see https://github.com/TheGrowingPlant/symfony.plugin.zsh
I remove all unused aliases and remove support of app/console (sf 2).
The plugin also works with syntax-highlighting.
=> Use custom symfony plugin

default.config.yml
=> Remove wkhtmltopdf from default homebrew cask packages

default.config.yml, roles/manage_services/tasks/main.yml, roles/minio/templates/minio.plist.j2
Fix #68 
The issue with sudo come from the last releases of Ansible (> 2.7) where `  become: "{{ item.sudo|default(false) }}"` no longer works.
To fix that I split the task in 2: root services and user services.
I clean up the error handling for start/stop state.
=> Rewrite manage_services role to fix issue with sudo

roles/nginx/tasks/main.yml
Bypass https://discourse.brew.sh/t/brews-curl-openssl-cant-resolve-localhost-hostnames-set-up-in-dnsmasq-system-curl-has-no-issue/5327/5
=> Set nginx vhost in /etc/hosts

default.config.yml, roles/nginx/tasks/main.yml, roles/nginx/templates/sites/default.j2, roles/nginx/templates/sites/site.j2, roles/nginx/vars/main.yml
Instead of generate one certificate per site, we generate only one certificate for all sites.
=> Generate only one certificate for nginx instead of one per site

roles/common/vars/main.yml, roles/dotfiles/templates/zshrc.j2
`ruby` is now linked to ruby 3
=> Stay on ruby 2

roles/git/templates/gitconfig.j2
To avoid this warning after each `git init`
=> Set git default branch to main

roles/php/tasks/install_php.yml, roles/php/vars/main.yml
Xdebug 3.2 only works with PHP 8, see https://xdebug.org/docs/compat
=> Fix xdebug install for php < 8.0

roles/nginx/templates/conf/drupal.j2
Fix `upstream sent too big header while reading response header from upstream`
=> Configure drupal config for nginx

roles/mkcert/tasks/main.yml
We think it's no longer useful
=> :fire: Remove pip installed certifi

default.config.yml, roles/php/tasks/install_php.yml, roles/php/vars/main.yml
Since this morning, I have issues with PHP 7.4 or PHP 8.0 when I install pecl extensions or xdebug. The only ressource I found is https://bugs.xdebug.org/view.php?id=2167
We don't use these versions much anymore, so I added options not to install xdebug or other extensions for these specific versions
=> PHP - Add options to not install extensions or xdebug

playbooks/setup.yml, roles/logrotate/handlers/main.yml, roles/logrotate/tasks/main.yml, roles/logrotate/templates/php-fpm.j2, roles/logrotate/vars/main.yml
Fix #190.
Maybe daily is to much but honestly I don't think we need to keep many months of logs.
Result after one day: 
php-fpm.log
php-fpm.log-20240130.gz => 287M (was 5.8G 😅 before compression)
We could also configure logrotate on nginx logs. 
On my laptop, `error.log` use 1.2G and some website access logs are bigger than 200M.
=> Add role to use logrotate for php-fpm log

Makefile, README.md, scripts/bootstrap.sh, scripts/install-ansible.sh
We need to use ansible < 2.18 because of OVH shared hosting (old version of Python).
We can now specify an ansible version when we bootstrap.
You need to reset you ansible install : 
```
$ pipx uninstall ansible
$ pipx uninstall ansible-core
$ dev install-ansible ansible_version_spec="<2.18"
```
=> Allow to configure ansible version when bootstrap

roles/common/vars/main.yml
This packages are now installed in `bootstrap.sh` before setup.
This will fix the following warnings: 
```
Warning: python@3.13 3.13.1 is already installed and up-to-date.
To reinstall 3.13.1, run:
brew reinstall python@3.13
Warning: openssl@3 3.4.0 is already installed and up-to-date.
To reinstall 3.4.0, run:
brew reinstall openssl@3
```
=> Remove homebrew base packages already installed during bootstrap

roles/common/vars/main.yml
Fix the following errors : 
```
Error: ruby@2.7 has been disabled because it is not supported upstream! It was disabled on 2024-06-15.
```
```
failed: [127.0.0.1] (item=homebrew/cask-fonts) => changed=false 
ansible_loop_var: item
item: homebrew/cask-fonts
msg: |-
added: 0, unchanged: 0, error: failed to tap: homebrew/cask-fonts due to Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.
failed: [127.0.0.1] (item=homebrew/cask-versions) => changed=false 
ansible_loop_var: item
item: homebrew/cask-versions
msg: |-
added: 0, unchanged: 0, error: failed to tap: homebrew/cask-versions due to Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```
We can now …
=> Remove disabled packages and deprecated taps

roles/nginx/templates/conf/wordpress.j2
Fix `upstream sent too big header while reading response header from upstream`
=> Fix too big header error with nginx for wordpress
