Dalokae/mac-playbook

roles/common/tasks/main.yml

Fix install of curl when is not installed

---

Makefile
README.md
roles/dotfiles/templates/zshrc.j2
roles/nginx/tasks/certificates.yml
roles/nginx/templates/sites/site.j2
roles/nginx/vars/main.yml

Use https://github.com/FiloSottile/mkcert
Upgrade:
* upgrade: `dev upgrade`
* setup nginx: `dev setup-nginx`
* to setup mkcert: `dev setup-mkcert`
Then restart all browsers.

Use mkcert for certificates

---

roles/mariadb/tasks/main.yml

See https://github.com/Homebrew/brew/issues/5783

Add a KEEP_DIR file in /usr/local/etc/my.cnf.d/ to avoid deletion

---

default.config.yml

Force to use Node 10, without that node move to version 12

Use nodejs 10

---

default.config.yml
playbooks/setup.yml
roles/dotfiles/templates/zshrc.j2
roles/node/tasks/main.yml
roles/node/templates/load_node.j2

Create a role to add node 10 to PATH

Add node 10 role

---

default.config.yml
playbooks/setup.yml
roles/postgresql/handlers/main.yml
roles/postgresql/tasks/main.yml

Add postgresql role

---

roles/nginx/templates/conf/symfony-flex.j2
roles/nginx/templates/nginx.conf.j2
roles/nginx/templates/sites/site.j2

* add request_id as a header "X-Request-ID"
* add request_id to logs
* add request_id in Symfony envs

Add request_id to nginx

---

roles/check_sudo_access/tasks/main.yml

* No more writing to filesystem, we only execute an "echo"  -> faster
* no more exception in the console
* translate to english

Better way to check is sudo password is correct, no more file writing

---

playbooks/dotfiles.yml
roles/git/templates/gitconfig.j2

> --preserve-merges is getting deprecated in favour of --rebase-merges

Use "merges" instead of "preserve"

---

roles/dotfiles/templates/zshrc.j2

See https://docs.python-guide.org/starting/install3/osx/

add homebrew python to PATH

---

default.config.yml
roles/dotfiles/templates/zsh_aliases.j2

Allow override of ZSH aliases

---

default.config.yml
roles/postgresql/handlers/main.yml
roles/postgresql/tasks/main.yml

Force use of postgresql@11

---

default.config.yml
roles/dotfiles/templates/zshrc.j2
roles/postgresql/handlers/main.yml
roles/postgresql/tasks/main.yml
roles/postgresql/templates/load_postgresql.j2

* Add variable to set postgresql version
* get brew prefix to access postgresql bin

Fix integration of PostgreSQL 11

---

default.config.yml

https://intellij-support.jetbrains.com/hc/en-us/articles/206544819-How-to-collect-remote-log-for-XDebug

Add config for xdebug remote log

---

default.config.yml
roles/dotfiles/tasks/main.yml
roles/dotfiles/templates/zshrc.j2

Fix #61 #62 
For extra config, the user must use `~/.zshrc.local`.

Better customization of zsh plugins

---

roles/git/templates/gitconfig.j2

https://twitter.com/viktorklang/status/1214898430964838400

New format for "git br"

---

Makefile
roles/dotfiles/templates/zshrc.j2
roles/nginx/tasks/certificates.yml
roles/nginx/vars/main.yml

Also: 
* rename cacert.pem into cert.pem
* ~~remove REQUESTS_CA_BUNDLE env var~~

Use OpenSSL@1.1

---

Makefile

See https://github.com/TheGrowingPlant/mac-playbook/issues/53#issuecomment-600485434

Fix python and open ssl

---

Makefile

Use /usr/local/opt/openssl@1.1 to avoid issue with openssl update

---

default.config.yml
roles/php/vars/main.yml

:fire: Remove fixed xdebug version

---

playbooks/manage_services.yml
roles/ansible/tasks/main.yml
roles/blackfire/handlers/main.yml
roles/cleanup/tasks/main.yml
roles/common/tasks/main.yml
roles/dev_bin/tasks/main.yml
roles/dnsmasq/handlers/main.yml
roles/dnsmasq/tasks/main.yml
roles/dotfiles/tasks/main.yml
roles/git/tasks/main.yml
roles/mailhog/handlers/main.yml
roles/manage_services/tasks/main.yml
roles/mariadb/handlers/main.yml
roles/mariadb/tasks/main.yml
roles/minio/tasks/main.yml
roles/nginx/handlers/main.yml
roles/nginx/tasks/main.yml
roles/postgresql/handlers/main.yml
roles/postgresql/tasks/main.yml
roles/redis/handlers/main.yml
roles/redis/tasks/main.yml
roles/sudoers/tasks/main.yml
scripts/generate-ansible-password

Translate all names and scripts

---

roles/git/templates/gitconfig.j2

Remove git noprefix option to avoid issue with hooks

---

playbooks/setup.yml
roles/cleanup/tasks/main.yml

Cleanup - brew services 

---

Makefile
roles/postgresql/tasks/main.yml

I don't know if it's really relevant because of issues on OSX/BSD when sorting UTF-8 strings.
But maybe it could help in other situation to be iso production. 
Also maybe the target need some kind of warning about database reset.

Add a makefile target to change default locale to en_US.UTF-8 for PostgreSQL

---

config_php.yml
default.config.yml
playbooks/dotfiles.yml
playbooks/manage_services.yml
playbooks/setup.yml
playbooks/setup_nginx.yml
roles/php/tasks/install_php.yml
roles/php/templates/load_php.j2
roles/php/templates/sphp.sh.j2

Keep current php version between dev setup/upgrade.
No more:
* current php version = 7.2
* dev setup
* php -v -> 7.4
Also fix #81

Keep current php version

---

roles/mariadb/tasks/main.yml

Use root to change mariadb root password

---

roles/dotfiles/templates/editorconfig.j2

https://app.clubhouse.io/wizifarm/story/22846/utiliser-des-espaces-dans-les-fichiers-neon

EditorConfig : Remove custom config for neon

---

default.config.yml
roles/composer/tasks/main.yml

Upgrade:
```shell
$ composer global remove hirak/prestissimo
```

Move to Composer 2

---

local-homepage/index.php
roles/mariadb/templates/local-homepage/config.php.j2
roles/nginx/templates/local-homepage/config.php.j2

* Dynamic loading of configs
* Update bootstrap
* Remove reference to rabbitmq
* new layout similar to phpinfo()

:art: Cleanup local homepage

---

roles/composer/tasks/main.yml
roles/composer/vars/main.yml

Install both major versions of composer

---

Makefile
requirements.txt
scripts/bootstrap.sh

add requirements.txt for ansible install/upgrade

---

local-homepage/index.php
local-homepage/xdebug-info.php

Add xdebug_info() page

---

requirements.txt

```shell
$ pip uninstall ansible ansible-core ansible-base
$ pip install --force-reinstall ansible ansible-core
```

:arrow_up: ansible

---

default.config.yml
roles/git/templates/gitconfig.j2

Add config for git aliases

---

default.config.yml
roles/blackfire/tasks/main.yml
roles/blackfire/vars/main.yml
roles/php/tasks/install_php.yml
roles/php/tasks/main.yml
roles/php/templates/sphp.sh.j2
roles/php/vars/main.yml
scripts/xdebug.sh

We must remove installed php versions with `brew list | grep php` then for each package `brew uninstall XXXX`

Move to shivammathur/php and allow PHP 8.1

---

playbooks/setup.yml
roles/wp_cli/tasks/main.yml
roles/wp_cli/vars/main.yml

Add role for wp-cli

---

roles/git/files/gitignore_global

- order rules
- add documentation when possible
- add rule for .fleet

gitignore_global enhancements

---

roles/dotfiles/tasks/main.yml
roles/dotfiles/templates/zshrc.j2

Replace DISABLE_UPDATE_PROMPT

---

roles/nginx/tasks/main.yml

Set exec right on HOME directory to avoid issue with nginx

---

roles/nginx/vars/main.yml

Add laravel to nginx sites types

---

playbooks/setup.yml
roles/bat/tasks/main.yml
roles/bat/templates/config.j2
roles/bat/vars/main.yml
roles/common/vars/main.yml

Add a custom role for bat (cat) to have syntax highlighting for custom ssh config

Add bat role with custom config

---

default.config.yml

To upgrade :
```
dev setup
brew services stop postgresql@14
brew services stop postgresql@13
brew postgresql-upgrade-database 
brew uninstall postgresql@13
dev restart
```

:arrow_up: move to postgresql 14

---

playbooks/setup.yml
roles/drush/tasks/main.yml
roles/drush/vars/main.yml

* Install Drush Launcher
* Install Drush 8 for Drupal 7
To test: `dev setup tags=drush`

Add role for drush

---

default.config.yml

To upgrade :
```
dev setup
brew services stop postgresql@15
brew services stop postgresql@14
brew postgresql-upgrade-database 
brew uninstall postgresql@14
dev restart
```

Move to postgresql 15

---

default.config.yml
roles/dotfiles/templates/zshrc.j2

Fix #181
Related to #179 : the fix I made broke the password pass between ansible and sudo.
`dev dotfiles` must be run to set `HOMEBREW_CACHE` export

:bug: Fix issue between homebrew/sudo and ansible become

---

roles/nginx/templates/conf/drupal.j2

See https://www.drupal.org/project/drupal/issues/3368769#comment-15119875

Update drupal config for nginx to fix issue with css

---

roles/nginx/templates/sites/site.j2

I think is better to set the value to `true` by default

Set nginx redirect_to_https var to true by default

---

roles/common/vars/main.yml

Adapt playbook for MacOs Sonoma

---

Makefile
README.md
UPGRADE.md
default.config.yml
playbooks/manage_services.yml
playbooks/setup.yml
roles/composer/vars/main.yml
roles/dev_bin/tasks/main.yml
roles/dnsmasq/vars/main.yml
roles/dotfiles/tasks/main.yml
roles/dotfiles/templates/zshrc.j2
roles/drush/tasks/main.yml
roles/drush/vars/main.yml
roles/git/templates/gitconfig.j2
roles/mailpit/templates/plist.j2
roles/mailpit/vars/main.yml
roles/mariadb/tasks/main.yml
roles/mariadb/vars/main.yml
roles/minio/tasks/main.yml
roles/minio/templates/minio.plist.j2
roles/mkcert/tasks/main.yml
roles/nginx/vars/main.yml
roles/php/tasks/install_php.yml
roles/php/templates/php-fpm.conf.j2
roles/php/vars/main.yml
roles/wp_cli/vars/main.yml
scripts/bootstrap.sh
scripts/xdebug.sh

Add supports of Mac Silicon.
Include some cleanup like drush launcher or the simplification of the openssl certificates part

Mac Silicon

---

Makefile
renovate.json
requirements.txt
roles/common/vars/main.yml
roles/dotfiles/templates/zprofile.j2
scripts/bootstrap.sh

Fix #209
1. dev dotfiles
2. pipx install --include-deps ansible
3. Old ansible binaries must be deleted with : `rm /opt/homebrew/bin/ansible*`

Install ansible with pipx

---

Makefile
README.md
roles/dotfiles/templates/zprofile.j2
scripts/bootstrap.sh

See https://github.com/pypa/pipx/issues/1226
1. dev dotfiles
2. Reload du terminal
3. pipx install --include-deps ansible --force

Set pipx HOME to avoid issue with ansible

---

default.config.yml
playbooks/setup.yml
roles/redis/handlers/main.yml
roles/redis/tasks/main.yml

We don't use Redis.
After merge : `brew uninstall redis`

:fire: Remove Redis

---

default.config.yml
roles/dotfiles/templates/zprofile.j2
roles/mariadb/tasks/main.yml
roles/mariadb/templates/load_mariadb.j2
roles/postgresql/tasks/main.yml

Related to #214
@nclsHart you need to add `mariadb_version: 11.4` to your config.yml

Allow to configure the version of mariadb to install/use

---

default.config.yml
roles/git/templates/gitconfig.j2

I will try https://github.com/MitMaro/git-interactive-rebase-tool

Allow config of git sequence editor

---

scripts/bootstrap.sh

Needed to generate hash or password with ansible.

Inject passlib for ansible

---

roles/php/tasks/install_php.yml

Fix removing of extensions in php.ini

---

default.config.yml
roles/php/tasks/install_php.yml

Update default php version and only keep 8.3 and 8.4

---

roles/php/tasks/install_php.yml

I forgot to push a commit in https://github.com/Dalokae/mac-playbook/pull/229 ...

:bug: Fix wrong usage of php_current_version_extensions
